# Generated by Django 2.2.9 on 2022-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Articles', 'Articles'), ('International Reports', 'International Reports'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
    ]
