# Generated by Django 2.2.9 on 2022-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('Team', 'Team'), ('Alumini', 'Alumini')], default='Team', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='associated_contact',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Conference', 'Conference'), ('Books', 'Books'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
