# Generated by Django 3.2.9 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters'), ('Books', 'Books'), ('Conference', 'Conference')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Editorial Boards', 'Editorial Boards'), ('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
    ]
