# Generated by Django 2.2.9 on 2022-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220830_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_current_team_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('International Reports', 'International Reports'), ('Articles', 'Articles')], default='Journal', max_length=60),
        ),
    ]
