# Generated by Django 2.2.9 on 2022-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220924_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=3000, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('International Reports', 'International Reports'), ('Books', 'Books'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Alumini', 'Alumini'), ('Team', 'Team')], default='Team', max_length=60),
        ),
    ]
