# Generated by Django 2.2.9 on 2023-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_homepage_youtube_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map_Location',
        ),
        migrations.DeleteModel(
            name='View_count',
        ),
        migrations.AlterModelOptions(
            name='gallery_image',
            options={'verbose_name': 'Images'},
        ),
        migrations.AddField(
            model_name='gallery_image',
            name='image_Category',
            field=models.CharField(choices=[('Publication', 'Publication'), ('Gallery', 'Gallery')], default='Galelry', max_length=60),
        ),
    ]
