# Generated by Django 2.2.9 on 2022-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220924_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Publication',
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Team', 'Team'), ('Alumini', 'Alumini')], default='Team', max_length=60),
        ),
    ]
