# Generated by Django 2.2.9 on 2022-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20221007_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('International Reports', 'International Reports'), ('Book Chapters', 'Book Chapters'), ('Conference', 'Conference'), ('Books', 'Books')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Editorial Boards', 'Editorial Boards'), ('Invited Talks', 'Invited Talks'), ('Conference Presentation', 'Conference Presentation')], default='Invited Talks', max_length=60),
        ),
    ]
