# Generated by Django 2.2.9 on 2022-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220903_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Articles', 'Articles'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
    ]
