# Generated by Django 2.2.9 on 2022-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20221013_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Books', 'Books'), ('Book Chapters', 'Book Chapters'), ('Conference', 'Conference'), ('International Reports', 'International Reports')], default='Journal', max_length=60),
        ),
    ]
