# Generated by Django 2.2.9 on 2022-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220924_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reasearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('category', models.CharField(choices=[('Editorial Boards', 'Invited Talks'), ('Invited Talks', 'Invited Talks'), ('Conference Presentation', 'Invited Talks')], default='Invited Talks', max_length=60)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Book Chapters', 'Book Chapters'), ('Conference', 'Conference'), ('Books', 'Books'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
    ]
