# Generated by Django 2.2.9 on 2022-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220924_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Journal', 'Journal'), ('Books', 'Books'), ('Conference', 'Conference'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Editorial Boards', 'Editorial Boards'), ('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
    ]
