# Generated by Django 2.2.9 on 2022-10-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20221013_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('International Reports', 'International Reports'), ('Book Chapters', 'Book Chapters'), ('Books', 'Books')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks'), ('Editorial Boards', 'Editorial Boards')], default='Invited Talks', max_length=60),
        ),
    ]
