# Generated by Django 2.2.9 on 2022-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220904_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_count',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Articles', 'Articles'), ('International Reports', 'International Reports'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
    ]
