# Generated by Django 2.2.9 on 2022-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220904_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Articles', 'Articles'), ('International Reports', 'International Reports')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='view_count',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
