# Generated by Django 2.2.9 on 2022-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220924_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Book Chapters', 'Book Chapters'), ('Journal', 'Journal'), ('Conference', 'Conference'), ('International Reports', 'International Reports')], default='Journal', max_length=60),
        ),
    ]
