# Generated by Django 3.2.9 on 2022-10-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20221006_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map_Locations',
            new_name='Map_Location',
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Books', 'Books'), ('Book Chapters', 'Book Chapters'), ('International Reports', 'International Reports'), ('Conference', 'Conference')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Conference Presentation', 'Conference Presentation'), ('Editorial Boards', 'Editorial Boards'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Alumini', 'Alumini'), ('Team', 'Team')], default='Team', max_length=60),
        ),
    ]
