# Generated by Django 2.2.9 on 2022-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20221013_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('International Reports', 'International Reports'), ('Conference', 'Conference'), ('Book Chapters', 'Book Chapters'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks'), ('Editorial Boards', 'Editorial Boards')], default='Invited Talks', max_length=60),
        ),
    ]
