# Generated by Django 3.2.9 on 2022-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20221006_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('International Reports', 'International Reports'), ('Conference', 'Conference'), ('Book Chapters', 'Book Chapters'), ('Books', 'Books')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Conference Presentation', 'Conference Presentation'), ('Editorial Boards', 'Editorial Boards'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
    ]
