# Generated by Django 2.2.9 on 2022-10-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20221012_1815'),
        ('portfolio', '0009_auto_20221013_1641'),
    ]

    operations = [
    ]
