# Generated by Django 3.2.9 on 2022-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20221006_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Books', 'Books'), ('International Reports', 'International Reports'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Invited Talks', 'Invited Talks'), ('Editorial Boards', 'Editorial Boards'), ('Conference Presentation', 'Conference Presentation')], default='Invited Talks', max_length=60),
        ),
    ]
