# Generated by Django 3.2.9 on 2022-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20221004_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('International Reports', 'International Reports'), ('Books', 'Books'), ('Book Chapters', 'Book Chapters'), ('Conference', 'Conference')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Editorial Boards', 'Editorial Boards'), ('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
    ]
