# Generated by Django 2.2.9 on 2022-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_ipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=3000)),
                ('subject', models.CharField(max_length=3000)),
                ('affilation', models.CharField(max_length=3000)),
                ('message', models.TextField()),
            ],
        ),
    ]
