# Generated by Django 2.2.9 on 2022-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20221006_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Book Chapters', 'Book Chapters'), ('Books', 'Books'), ('International Reports', 'International Reports'), ('Conference', 'Conference'), ('Journal', 'Journal')], default='Journal', max_length=60),
        ),
    ]
