# Generated by Django 2.2.9 on 2022-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20221006_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Books', 'Books'), ('International Reports', 'International Reports'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Conference Presentation', 'Conference Presentation'), ('Editorial Boards', 'Editorial Boards'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Team', 'Team'), ('Alumini', 'Alumini')], default='Team', max_length=60),
        ),
    ]
