# Generated by Django 3.2.9 on 2022-10-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20221006_1144'),
        ('portfolio', '0012_auto_20221006_1936'),
    ]

    operations = [
    ]
