# Generated by Django 2.2.9 on 2022-09-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('International Reports', 'International Reports'), ('Articles', 'Articles')], default='Journal', max_length=60),
        ),
    ]
