# Generated by Django 2.2.9 on 2022-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.EmailField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Journal', 'Journal'), ('International Reports', 'International Reports'), ('Articles', 'Articles'), ('Conference', 'Conference')], default='Journal', max_length=60),
        ),
    ]
