# Generated by Django 2.2.9 on 2022-09-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220907_0443'),
        ('portfolio', '0014_alter_project_category'),
    ]

    operations = [
    ]
