# Generated by Django 4.1.1 on 2022-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Journal', 'Journal'), ('Articles', 'Articles'), ('International Reports', 'International Reports')], default='Journal', max_length=60),
        ),
    ]
